### ISSUE TITLE
iOS build error Undefined symbol

### ISSUE THREAD

**Issue by dev-twoweb** [dcvz/react-native-zendesk#11]
RN 0.57

Undefined symbol: ZendeskSDK.RequestUiConfiguration.__allocating_init() -> ZendeskSDK.RequestUiConfiguration
![Error](https://i.ibb.co/8MVgjZP/Captura-de-Tela-2019-08-29-a-s-11-06-09.png)

Issue started to occur after upgrading to XCode 10.3

**Comment by dev-twoweb** [comment]
Issue started to occur after upgrading to XCode 10.3

**Comment by dcvz** [comment]
@dev-twoweb are you still experiencing this on the latest version + Xcode?

**Comment by dcvz** [comment]
I will close this for inactivity
