### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2.1 compiler

### ISSUE THREAD

**Issue by llaine** [dcvz/react-native-zendesk#4]
I'm getting this issue when trying to run the project on the simulator.

Is there no backward compat with Swift?

**Comment by LeonidVeremchuk** [comment]
Found one workaround:
I am use fork from another repo: 

Just update your **package.json**

    "react-native-zendesk": "git://github.com/Snailapp/react-native-zendesk.git#1.0.5",

**Comment by dcvz** [comment]
A new version has been published which should resolve this issues: https://github.com/dcvz/react-native-zendesk/releases/tag/v2.0.0
