### ISSUE TITLE
Build Error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by dev-twoweb** [dcvz/react-native-zendesk#7]
I tried installing on ios, but presented the following error in build:
![Captura de Tela 2019-03-18 às 17 40 26](https://user-images.githubusercontent.com/43548289/54562081-fb3c2d80-49a4-11e9-8f1f-1ef906e51080.png)
Any suggestion?

**Comment by dev-twoweb** [comment]
The solution to my problem was:
1 - Open ios/YourAppName.xcodeproj in Xcode
2- Right-click on Your App Name in the Project Navigator on the left, and click New File…
3 -Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
4 - when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
This should fix the problem

**Comment by dcvz** [comment]
A new version has been published which should resolve this issues: https://github.com/dcvz/react-native-zendesk/releases/tag/v2.0.0
