### ISSUE TITLE
Failed build: No such module 'Zendesk'

### ISSUE THREAD

**Issue by cspicuzza** [dcvz/react-native-zendesk#8]
I'm using v2.0.0 and builds are failing with the error:

```
Compiling RNZendesk.swift

❌ /node_modules/react-native-zendesk/ios/RNZendesk/RNZendesk.swift:11:8: no such module 'ZendeskSDK'

```

Thanks for your time and effort building this package

**Comment by dcvz** [comment]
Have you installed via `cocoapods` using auto linking in RN 0.60?

**Comment by cspicuzza** [comment]
> Have you installed via `cocoapods` using auto linking in RN 0.60?

We are auto-linking using RN 0.59 without `cocoapods`.

**Comment by dcvz** [comment]
@cspicuzza `RN 0.59` doesn't have autolinking. The latest version of this lib is only supporting `RN 0.6` as it changes the way the frameworks are referenced.

**Comment by huynguyen3tiki** [comment]
hi @dcvz . which tag version for rn 0.59? 
tks u.

**Comment by dcvz** [comment]
@huynguyen3tiki 1.0.3 would be the last version to support `0.59`
